# Generated by Django 5.0.7 on 2024-07-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
